# Generated by Django 4.2.8 on 2024-01-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_image',
            field=models.ImageField(default='background.jpg', upload_to=''),
        ),
    ]
