# Generated by Django 4.2.8 on 2024-01-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_username_task_username_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
