# Generated by Django 4.2.8 on 2024-01-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_images',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
