# Generated by Django 4.2.8 on 2024-02-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_user_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='partakers',
            field=models.IntegerField(default=0),
        ),
    ]
