# Generated by Django 4.2.8 on 2024-03-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_p2p_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='period',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
