# Generated by Django 4.2.8 on 2024-03-05 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_task_number_task_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p2p_transactions',
            old_name='Task_owner',
            new_name='task_owner',
        ),
    ]
